name: AI Code Review and Comment Responder

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  ai_code_review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/scripts/requirements.txt

      - name: AI Code Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ADD_INLINE_COMMENTS: ${{ vars.ADD_INLINE_COMMENTS }}
          CONTEXT_LINES: ${{ vars.CONTEXT_LINES }}
          ADD_WHOLE_PR_COMMENT: ${{ vars.ADD_WHOLE_PR_COMMENT }}
        run: python .github/scripts/ai_code_review.py

  ai_comment_responder:
    if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '@pr-ai')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/scripts/requirements.txt

      - name: Respond to Comment with AI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python .github/scripts/respond_to_comment.py
